### ISSUE TITLE
Google search results not getting redirected to new wiki

### ISSUE THREAD

**Issue by sadegr** [proEndreeper/RSWikiRedirector#3]
The old wiki recently changed their domain name from wikia.com to fandom.com, causing this extensions to no longer redirect old wiki pages to the new wiki (oldschool.wiki).

**Comment by sadegr** [comment]
Never mind, I realized that a pull request had already been merged to fix this issue but for some reason the Chrome extension appeared to already be up to date on my machine. I just uninstalled and reinstalled it and everything works fine now.

**Comment by sadegr** [comment]
Reopening, I realized that the redirection is no longer working when I click a Google search result. I have to refresh the page in order to be redirected to the new wiki. Typing the URL directly into my address bar does cause the page to be redirected to the new wiki.

**Comment by LitePenguins** [comment]
I'm getting this same issue.

**Comment by proEndreeper** [comment]
Looking into this, it might be a result of it using a cached page instead of going through the web requests api. I managed to get it to redirect correctly now, as it now checks upon navigation rather than upon a new web request. Probably will throw warnings that the permissions changed, as I now have to request a tab to redirect right before the navigation happens.

Version 1.3.0 has been tested on both Chrome and Firefox and appears to work, so let me know if the bug is fixed when your extension updates.

**Comment by proEndreeper** [comment]
My testing so far has indicated that the fix works reliably, so I'm closing this issue.

**Comment by Jules-A** [comment]
It's broken for me with Nightly since V1.4.

**Comment by proEndreeper** [comment]
What browser do you use?

**Comment by Jules-A** [comment]
Firefox Nightly, like I mentioned in the previous post.

**Comment by proEndreeper** [comment]
I just installed Firefox Nightly v67.0a1 and it worked fine, could you tell me what version of Nightly you are running? (3 Lines -> Help -> About Nightly)

**Comment by Jules-A** [comment]
25th of Feb build. I did some further testing and it worked on a new profile so I tried removing the extension on the existing profile and re-installing and sure enough it worked.
